---
# handlers file for secInsight_6.x

# restart Osquery
- name: Restart osquery
  service:
    name: osqueryd
    state: restarted
#restart Filebeat
- name: Restart filebeat
  service:
    name: filebeat
    state: restarted
